arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 80
singleQuote: false
tabWidth: 4
trailingComma: all

overrides:
  - files: ".sol"
    options:
      compiler: "0.8.17"
      tabWidth: 4
      printWidth: 80
      singleQuote: false
      bracketSpacing: false
      explicitTypes: always
  - files: ".ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
